stages:
  - test

test:
  stage: test
  image: alpine:3
  before_script:
    - apk add bash bc coreutils
    - ln -fs /usr/bin/awk /bin/awk
    - ln -fs /usr/bin/cut /bin/cut
  script:
    - bash -c 'cd ./sample/ && bash ./incrbuild_funcTest.sh'
    - bash -c 'cd ./sample/ && bash ./incrbuild_unitTest.sh; [ ${?} -eq 2 ]'
    - bash -c 'cd ./sample/ && bash ./wrapper_multipleTest.sh; [ ${?} -eq 4 ]'
    - bash -c 'cd ./sample/ && bash ./wrapper_singleTest.sh'
    - bash -c 'cd ./tests/ && bash ./adhocFunctionNamesTest.sh'
    - bash -c 'cd ./tests/ && bash ./fail_FailAbortTest.sh; [ ${?} -eq 1 ]'
    - bash -c 'cd ./tests/ && bash ./fail_adhocFunctionNamesTest.sh'
    - bash -c 'cd ./tests/ && bash ./fail_jshuSetupTest.sh; [ ${?} -eq 1 ]'
    - bash -c 'cd ./tests/ && bash ./fail_jshuTeardownTest.sh; [ ${?} -eq 1 ]'
    - bash -c 'cd ./tests/ && bash ./wrapper_unfinishedTest.sh'
  artifacts:
    paths:
      - sample/results/xunit/
      - tests/results/xunit/
